### PR TITLE
Allow using true/false strings in package.json private field

### PR DESCRIPTION
**Pull request by ohana54**

### CODE REVIEW

**Comment by bluelovers** [comment]
is there has any npm like , use the string boolean ?

**Comment by ohana54** [comment]
Not sure I fully understand the question, the reason for the PR is that npm client does allow using the strings "true"/"false" for the `private` field.
My project does some manipulations on package.json files so I needed to support this as well.

**Comment by bluelovers** [comment]
new version published and also update to new schema

**Comment by ohana54** [comment]
Thank you!!

**Comment by ohana54** [comment]
Hi again :)
It seems that the `private` field declaration in the auto-generated `CoreProperties` interface is overriding this change. Is there any way to fix that?
I can try to submit another PR to https://github.com/SchemaStore/schemastore if that's the right thing to do.

**Comment by bluelovers** [comment]
u should import this file
https://github.com/bluelovers/ws-ts-type/blob/master/packages/package-dts/package-json.ts

**Comment by ohana54** [comment]
I changed my import from
`import IPackageJson from '@ts-type/package-dts'`
to
`import IPackageJson from '@ts-type/package-dts/package-json'`

And got the same results (which AFAICT makes sense because the first one re-exports the second)

**Comment by bluelovers** [comment]
ok fix again

**Comment by ohana54** [comment]
https://github.com/SchemaStore/schemastore/pull/1082

**Comment by ohana54** [comment]
Finally my 2 PRs in other repos were merged, so I opened a new PR to update the schema - #2

**Pull request merged**
